# Generated by Django 3.0.6 on 2020-06-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_auto_20200604_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_model',
            name='following',
        ),
    ]
